# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/dhsavell/scriptoids
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: go build -o ./out/scriptoids cmd/main.go
      - run: ./out/sciptoids init --path ./out/scriptoid.hcl --name scriptoids --version 0.0.0 --entrypoint scriptoids
      - run: tar -cvf ./out/scriptoids.tar ./out/scriptoids ./out/scriptoid.hcl
      - store_artifacts:
          path: ./out
