# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2

jobs:
  setup:
    docker:
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/dhsavell/scriptoids
    steps:
      - checkout
      - run: go get -v -t -d ./...

  test:
    docker:
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/dhsavell/scriptoids
    steps:
      - run: go test -v ./...

  build:
    docker:
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/dhsavell/scriptoids
    steps:
      - run: go build -o ./out/scriptoids cmd/main.go

  create_scriptoid_artifact:
    docker:
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/dhsavell/scriptoids/out
    steps:
      - run: ./sciptoids init --path ./scriptoid.hcl --name scriptoids --version 0.0.0 --entrypoint scriptoids
      - run: tar -cvf ./scriptoids.tar ./scriptoids ./scriptoid.hcl
      - store_artifacts:
          path: .

workflows:
  version: 2
  test_and_build:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - build:
          requires:
            - test
      - create_scriptoid_artifact:
          requires:
            - build
